module.exports = function (grunt) {

    /**
     * Sequence of concatenation of forest files.
     * The first are the files of variables.
     */
    var Sequence = [
        'less-variables/defaults.less',
        'less-variables/' + grunt.option('scheme') + '.less',
        'less/style.less',
        'less/apartment_grid.less',
        'less/header.less',
        'less/top_bar.less',
        'less/search_form.less',
        'less/arrow_block.less',
        'less/property_grid.less',
        'less/agent_grid.less',
        'less/rangeslide.less',
        'less/property_slider.less',
        'less/footer.less',
        'less/service_section.less',
        'less/post_grid.less',
        'less/features_section.less',
        'less/testimonials_section.less',
        'less/property_carousel.less',
        'less/property_standart_grid.less',
        'less/city_grid.less',
        'less/partner_carousel.less',
        'less/contact_form2.less',
        'less/call_toaction1.less',
        'less/new_regions.less',
        'less/new_property_subscribe.less',
        'less/page_title_simple.less',
        'less/property_gallery.less',
        'less/mortage_calculator.less',
        'less/sidebar_searh_results.less',
        'less/single_property_details.less',
        'less/single_property_features.less',
        'less/property_share.less',
        'less/agents_carousel.less',
        'less/arrow_block_final.less',
        'less/home_bar.less',
        'less/counters.less',
        'less/slider_text.less',
        'less/property_price.less',
        'less/property_pageviews_chart.less',
        'less/sub_property_pagetitle.less',
        'less/sidebar_categories.less',
        'less/blog_calendar.less',
        'less/sidebar_recent_posts.less',
        'less/sidebar_tags.less',
        'less/sidebar_recent_comments.less',
        'less/blog_post_archive.less',
        'less/search_form2.less',
        'less/call_toaction2.less',
        'less/featured_carousel.less',
        'less/contact_form.less',
        'less/slider_form.less',
        'less/about_faq.less',
        'less/partners_small.less',
        'less/pagination.less',
        'less/single_post.less',
        'less/comments.less',
        'less/recent_property_block.less',
        'less/single_post.less',
        'less/comments.less',
        'less/search_alttype.less',
        'less/intro_page.less',
        'less/map_component.less',
        'less/pagination_prev_next.less',
        'less/error_page.less',
        'less/sign_in_form.less',
        'less/property_address.less',
        'less/single_property_description.less',
        'less/table_property_listing.less',
        'less/coming-soon.less',
        'less/faq_page.less',
        'less/question_form_sidebar.less',
        'less/single_question_page.less',
        'less/rate_article.less',
        'less/accordion.less',
        'less/sidebar_contact_form.less',
        'less/contact_map_light.less',
        'less/contact_map_dark.less',
        'less/main_contact_form.less',
        'less/under_maintenance.less',
        'less/preloader.less',
        'less/search_simple_icon.less',
        'less/agency_normal.less',
        'less/advertisement_block.less',
        'less/sidebar_property_price.less',
        'less/sidebar_property_price_for_rent.less',
        'less/agent_block.less',
        'less/sidebar_featured_agents.less',
        'less/sidebar_search2.less',
        'less/sidebar_agent.less',
        'less/property_floorplans_simple.less',
        'less/sidebar_featured.less',
        'less/property_documents_simple.less',
        'less/property_agent.less',
        'less/compare_table.less',
        'less/pagetitle_agent.less',
        'less/information_block_big.less',
        'less/pagetitle_agency.less',
        'less/agent_grid_fs.less',
        'less/area_tabs.less',
        'less/sidebar_agency.less',
        'less/property_standart.less',
        'less/search_form_small.less',
        'less/call_toaction3.less',
        'less/map_component_listing.less',
        'less/testmap.less',
        'less/account_property.less',
        'less/account_menu.less',
        'less/chat_window.less',
        'less/header_4.less',
        'less/account_properties_counters_list.less',
        'less/chat_users.less',
        'less/account_page.less',
        'less/light_search_form.less',
        'less/top_bar_4.less',
        'less/dark_pre_footer.less',
        'less/footer_2.less',
        'less/chat_users.less',
        'less/account_page.less',
        'less/header_2.less',
        'less/account_donat_chart.less',
        'less/testbyAlexei.less',
        'less/landing.less',
        'less/property_similar.less',
        'less/settings_window.less',
        'less/submit_property_wild_block.less'


    ];

    if (grunt.option('default-less-vars')) {
        var file_path = 'less-variables/' + grunt.option('default-less-vars') + '.less';
        Sequence.splice(1, 0, file_path);
    }

    return {
        less: {
            options: {
                separator: '\n'
            },

            src: Sequence,
            dest: 'less/concat.less'
        }
    };

};