//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGYatirim.Models.Sinif
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DbAdmin
    {
        public int AdminID { get; set; }
        public string AdSoyad { get; set; }
        public string EPosta { get; set; }
        public string Tel { get; set; }

        public string Sifre { get; set; }
        public Nullable<bool> Durum { get; set; }
        public Nullable<int> RolId { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }

       
        public string KullaniciNo { get; set; }
    
        public virtual DbYetki DbYetki { get; set; }
    }
}
