//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGYatirim.Models.Sinif
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbBlog
    {
        public int BlogID { get; set; }
        public string Baslik { get; set; }
        public string Resim { get; set; }
        public string icerik1 { get; set; }
        public string icerik2 { get; set; }
        public string icerik3 { get; set; }
        public string YazarAdSoyad { get; set; }
        public string YazarResim { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string EPosta { get; set; }
        public Nullable<bool> Durum { get; set; }
    }
}
