//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGYatirim.Models.Sinif
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Dbilan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dbilan()
        {
            this.DbilanGallery = new HashSet<DbilanGallery>();
            this.DbHareket = new HashSet<DbHareket>();
        }
    
        public int ilanID { get; set; }
        public string EmlakTipi { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string TamAdres { get; set; }
        public Nullable<decimal> TamFiyat { get; set; }
        public Nullable<decimal> MetreKareFiyat { get; set; }
        public string CokluResim { get; set; }
        public string Aciklama { get; set; }
        public string ilanNo { get; set; }
        public string AlanBoyutu { get; set; }
        public string KurulusYili { get; set; }
        public string AraziAlanı { get; set; }
        public string Banyo { get; set; }
        public string OdaSayisi { get; set; }
        public string Garaj { get; set; }
        public string Aidat { get; set; }
        public string BulunduguKat { get; set; }
        public string KatSayisi { get; set; }
        public Nullable<int> ilanOzellikIDD { get; set; }
        public Nullable<int> EmlakTipIDD { get; set; }
        public Nullable<int> ilanDurumIDD { get; set; }
        public Nullable<int> KonumIDD { get; set; }
        public Nullable<bool> Durum { get; set; }
        public string isitma { get; set; }
        public string Esyali { get; set; }
        public string KullanimDurumu { get; set; }
        public string Siteicerisinde { get; set; }
        public string KrediyeUygun { get; set; }
        public string Takasli { get; set; }
        public string TapuDurumu { get; set; }
        public string ZeminEtudu { get; set; }
        public string YapininDurumu { get; set; }
        public string YakitTipi { get; set; }

        [AllowHtml]
        public string OzelNor { get; set; }
        public string Balkon { get; set; }
        public string SiteAdi { get; set; }
        public string GoogleMapAdres { get; set; }
        public string KProfil { get; set; }
        public string KAdSoyad { get; set; }
        public string KMeslek { get; set; }
        public string KKisaAciklama { get; set; }
        public string KTel { get; set; }
        public string KEPosta { get; set; }
        public string VitrinResim { get; set; }
        public Nullable<bool> MOnay { get; set; }
        public string EPosta { get; set; }
        public string KullaniciNo { get; set; }
        public string ArsaImarDurum { get; set; }
        public string ArsaAdaNo { get; set; }
        public string ArsaParselNo { get; set; }
        public string ArsaPaftaNo { get; set; }
        public string ArsaKaks { get; set; }
        public string ArsaGabari { get; set; }
        public string PetrolAcilAlan { get; set; }
        public string PetrolKapaliAlan { get; set; }
        public string PetrolPompaSayisi { get; set; }
        public string ArabaSerisi { get; set; }
        public string ArabaModel { get; set; }
        public string ArabaYil { get; set; }
        public string ArabaVites { get; set; }
        public string ArabaKM { get; set; }
        public string ArabaKasaTipi { get; set; }
        public string ArabaMotorGucu { get; set; }
        public string ArabaMotorHacmi { get; set; }
        public string ArabaCekis { get; set; }
        public string ArabaRenk { get; set; }
        public string ArabaGarantili { get; set; }
        public string ArabaPlakaUyrugu { get; set; }
        public string TraktorMarka { get; set; }
        public string TraktorKabin { get; set; }
        public string TraktorVites { get; set; }
        public string TraktorMotorGücü { get; set; }
        public string TraktorSlinderSayisi { get; set; }
        public string TraktorCalismaSaati { get; set; }
        public string TraktorOnYukleyiciKepce { get; set; }
        public string TraktorOnLastik { get; set; }
        public string TraktorArkaLastik { get; set; }
    
        public virtual DbEmlakTipi DbEmlakTipi { get; set; }
        public virtual DbilanDurum DbilanDurum { get; set; }
        public virtual DbilanOzellik DbilanOzellik { get; set; }
        public virtual DbKonum DbKonum { get; set; }





      //  public List<DbilanGallery> ResimTablosu { get; set; } = new List<DbilanGallery>(); // Null Referans Hatasına düşmemek için



        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DbilanGallery> DbilanGallery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DbHareket> DbHareket { get; set; }
    }
}
