//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGYatirim.Models.Sinif
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbilanGallery
    {
        public int ilanGalleryID { get; set; }
        public Nullable<int> İlanIDD { get; set; }
        public string Ad { get; set; }
        public string URL { get; set; }
        public Nullable<System.DateTime> EklenmeTarihi { get; set; }
    
        public virtual Dbilan Dbilan { get; set; }
    }
}
