//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGYatirim.Models.Sinif
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DbiletisimForm
    {
        public int iletisimFormID { get; set; }
        [Required(ErrorMessage = "Ad Soyad Giriniz")]
        [MinLength(5, ErrorMessage = "Ad Soyad En Az 5 Karakter olabilir.")]
        [MaxLength(60, ErrorMessage = "Ad Soyad En Fazla 60 Karakter olabilir.")]
        public string AdSoyad { get; set; }



        [Required(ErrorMessage = "E Posta Giriniz")]
        [MinLength(10, ErrorMessage = "E Posta En Az 10 Karakter olabilir.")]
        [MaxLength(90, ErrorMessage = "E Posta En Fazla 90 Karakter olabilir.")]
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$", ErrorMessage = "Geçerli E Posta Giriniz! Formata Uygun Deðil!")]
        [DataType(DataType.EmailAddress)]
        public string EPosta { get; set; }

        [Required(ErrorMessage = "Telefon No Giriniz")]
        [MinLength(10, ErrorMessage = "Telefon No En Az 10 Karakter olabilir.")]
        [MaxLength(13, ErrorMessage = "Telefon No En Fazla 13 Karakter olabilir.")]
        public string Tel { get; set; }

        [Required(ErrorMessage = "Konu Baþlýgýný Giriniz")]
        [MinLength(15, ErrorMessage = "Konu Baþlýgý En Az 15 Karakter olabilir.")]
        [MaxLength(120, ErrorMessage = "Konu Baþlýgý En Fazla 120 Karakter olabilir.")]
        public string Konu { get; set; }


        [Required(ErrorMessage = "Mesaj Zorunlu")]
        [MinLength(70, ErrorMessage = "Mesajýnýz En Az 70 Karakter olabilir.")]
        [MaxLength(1500, ErrorMessage = "Mesajýnýz En Fazla 1500 Karakter olabilir.")]
        public string Mesaj { get; set; }
        //public string AdSoyad { get; set; }
        //public string EPosta { get; set; }
        //public string Tel { get; set; }
        //public string Konu { get; set; }
        //public string Mesaj { get; set; }
        public Nullable<bool> Durum { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    }
}
