//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGYatirim.Models.Sinif
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbiletisimBilgi
    {
        public int iletisimBilgiID { get; set; }
        public string Sube { get; set; }
        public string Adres { get; set; }
        public string Tel { get; set; }
        public string EPosta { get; set; }
        public string Harita { get; set; }
        public string Facebook { get; set; }
        public string Twetter { get; set; }
        public string instagram { get; set; }
        public Nullable<bool> Durum { get; set; }
    }
}
