//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGYatirim.Models.Sinif
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbKullanici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DbKullanici()
        {
            this.DbHareket = new HashSet<DbHareket>();
        }
    
        public int KullaniciID { get; set; }
        public string KisiAdi { get; set; }
        public string KisiSoyadi { get; set; }
        public string KullaniciNo { get; set; }
        public string Meslek { get; set; }
        public string EPosta { get; set; }
        public string Sifre { get; set; }
        public string Telefon { get; set; }
        public string KisaAciklama { get; set; }
        public string Face { get; set; }
        public string instagram { get; set; }
        public Nullable<int> KullaniciRolid { get; set; }
        public Nullable<bool> ilanOnaylandi { get; set; }
        public Nullable<bool> Durum { get; set; }
        public string Resim { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Sehir { get; set; }
        public string TamAdres { get; set; }
    
        public virtual DbYetki DbYetki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DbHareket> DbHareket { get; set; }
    }
}
