//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGYatirim.Models.Sinif
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbSlider
    {
        public int SliderID { get; set; }
        public string Resim { get; set; }
        public string Baslik { get; set; }
        public string KisaYazi { get; set; }
        public Nullable<bool> Durum { get; set; }
    }
}
