//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGYatirim.Models.Sinif
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbTemsilci
    {
        public int TemsilciID { get; set; }
        public string AdSoyad { get; set; }
        public string Makam { get; set; }
        public string EPosta { get; set; }
        public string Tel { get; set; }
        public string Facebook { get; set; }
        public string instagram { get; set; }
        public string Twetter { get; set; }
        public string WebSite { get; set; }
        public Nullable<bool> Durum { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string ProfilResim { get; set; }
    }
}
