//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGYatirim.Models.Sinif
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResimDeneme
    {
        public int ResimID { get; set; }
        public string ResimAd { get; set; }
        public Nullable<int> ialnID { get; set; }
    
        public virtual ialnlarDeneme ialnlarDeneme { get; set; }
    }
}
